all:
  children:
    k8s_cluster:
      children:
        k8s_masters:
          hosts:
            k8s-master-01:
              ansible_host: 198.19.249.169  # 마스터 노드 IP
              ansible_user: root
              node_role: master
        k8s_workers:
          hosts:
            # 워커 노드 추가 예시:
            k8s-worker-01:
              ansible_host: 198.19.249.76   # 워커 노드 IP
              ansible_user: root
              node_role: worker
            # k8s-worker-02:
            #   ansible_host: 198.19.249.xxx
            #   ansible_user: root
            #   node_role: worker
