# Production environment inventory for kubernetes cluster deployment
# This inventory describes a multi-node cluster with control plane and worker nodes
# See https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# for tips on building your inventory

# Configure 'ip' variable to bind kubernetes services on a different ip than the default iface
# We should set etcd_member_name for etcd cluster. The node that are not etcd members do not need to set the value,
# or can set the empty string value.
[kube_control_plane]
k8s-master-01 ansible_host=192.168.2.8 ansible_user=root node_role=master

[etcd:children]
kube_control_plane

[kube_node]
k8s-master-01 ansible_host=192.168.2.8 ansible_user=root node_role=master
k8s-worker-01 ansible_host=192.168.1.48 ansible_user=root node_role=worker
k8s-worker-02 ansible_host=192.168.1.49 ansible_user=root node_role=worker

[k8s_cluster:children]
kube_control_plane
kube_node 