# Master node (32 vCPU, 64GiB RAM, 4T SSD)

node_labels:
  node-role.kubernetes.io/control-plane: ""

# Reserve for k8s components
kube_memory_reserved: 8192Mi
kube_cpu_reserved: 2000m
kube_ephemeral_storage_reserved: 50Gi

# Reserve for system processes
system_memory_reserved: 8192Mi
system_cpu_reserved: 2000m
system_ephemeral_storage_reserved: 50Gi

# Summary for master node (32 vCPU, 64GiB RAM, 4T SSD):
# - Reserved for k8s components: 2 vCPU, 8GiB RAM, 50GiB storage
# - Reserved for system:         2 vCPU, 8GiB RAM, 50GiB storage
# - Available for workloads:    28 vCPU, 48GiB RAM, 3.9TiB storage
