all:
  children:
    k8s_cluster:
      children:
        k8s_masters:
          hosts:
            k8s-master-01:
              ansible_host: 198.19.249.97  # Master node IP
              ansible_user: root
              node_role: master
        k8s_workers:
          hosts:
            k8s-worker-03:
              ansible_host: 198.19.249.225  # Added by setup-cluster.sh
              ansible_user: root
              node_role: worker
            # Existing worker node
            k8s-worker-01:
              ansible_host: 198.19.249.137   # Worker node IP
              ansible_user: root
              node_role: worker
            # Newly added worker node
            k8s-worker-02:
              ansible_host: 198.19.249.74
              ansible_user: root
              node_role: worker
